POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3000/videos?search=node

###

PUT http://localhost:3000/videos/baed4197-e17d-4fce-acf8-4c55309e12e2
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3000/videos/6cffbd6c-6048-4270-8310-5f1a9444bfbc