POST https://primeiras-impressoes-com-node-js.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET https://primeiras-impressoes-com-node-js.onrender.com/videos

###

PUT https://primeiras-impressoes-com-node-js.onrender.com/videos/9547506c-757d-489b-b03c-8f6c331ca55d
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://primeiras-impressoes-com-node-js.onrender.com/videos/9547506c-757d-489b-b03c-8f6c331ca55d